### ISSUE TITLE
Laravel 6 support?

### ISSUE THREAD

**Issue by WimDeMeester** [petercoles/Multilingual-Language-List#2]
Hi, 

Are there plans to make this package installable in Laravel 6?

**Comment by petercoles** [comment]
Thanks for the prompt. It's done.

**Comment by WimDeMeester** [comment]
Thanks a lot!

**Comment by WimDeMeester** [comment]
I still seem to have problems installing the new version... When I update to laravel 6, I get the following message:

```
Installation request for petercoles/multilingual-language-list ^1.1 -> satisfiable by petercoles/multilingual-language-list[1.1.0, 1.1.2, 1.1.3, 1.1.4].
```

But the new version 1.15 can not be found... Any idea if I'm doing something wrong?

**Comment by petercoles** [comment]
It's not you. Turns out that github has changed how package updates can be recognised by packagist. Packagist now has up-to-date information and so it should work now.

I'm a little puzzled as to why it worked for me. It should have failed for me too, but maybe it picked up a locally cached version. So please let me know whether this works for you so that I can be sure it's fixed for everyone. Thanks.

**Comment by WimDeMeester** [comment]
Works fine now. Thanks!
