### ISSUE TITLE
"Mixed" locales not available for all major languages

### ISSUE THREAD

**Issue by Napia** [petercoles/Multilingual-Language-List#6]
Hello Peter, thank you for the package!
The 'Mixed Locales' part is exactly what I was looking for. Unfortunately I am having some troubles with it. I am trying to get a list of all major languages, but apparently this is not available for all of these languages. Then I am getting:
```
Symfony\Component\ErrorHandler\Error\FatalError 

  require(): Failed opening required '' (include_path='.:/usr/share/php')
```
I could go trough all the languages now by myself, but this is quite time consuming, so maybe you could provide a list of possible languages? 
Thank you :)!

**Comment by petercoles** [comment]
Sorry for the delay. I didn't understand the issue when I first looked at it, but I think I see what you mean now. To ensure that I've understood, if I get a list of all the "major" languages in English. The first (alphabetically) is Abkhazian, which I'd certainly never heard of and for which there is no language file available in the data source. Although I don't recognise the error that you're getting, I suspect that it is generated when the package can't read the non-existent file.

That needs fixing, but your request for a list of the languages for which mixed locales is possible also sounds like a good idea. Watch this space :).

**Comment by petercoles** [comment]
Two parts to this.

Firstly the bug that most likely caused the error you reported has been fixed in the latest release.

Secondly, I don't propose to provide a list of possible languages as it's likely to go out of date fairly quickly. However, I have included information (and code) towards to the bottom of the readme file to show how you can quickly and easily generate this yourself against whatever is the state of the underlying data at the time you need it.
